In [1]:
import torch
import numpy as np
import time

device = 'cuda' if torch.cuda.is_available() else 'cpu'

print(device)

cuda


In [8]:
# Define a probability tensor
probabilities = torch.tensor([0.1, 0.9])

# 10% or 0.1 => 0, 90% or 0.9 => 1; each probability points to the index of the probability in the tensor
# Draw 5 samples from the multinomial distribution
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples)

tensor([0, 0, 0, 1, 1, 1, 1, 1, 1, 1])


In [10]:
# This will concatenate our size-4 tensor with a new size-1 tensor
# This can be used in machine learning to concatenate a running prediction engine

tensor = torch.tensor([1, 2, 3, 4])
out = torch.cat((tensor, torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

In [11]:
# "Triangle Lower"
# As our predictions add up, we have an increasing amount of future and a decreasing amount of past

out = torch.tril(torch.ones(5, 5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [12]:
# "Triangle Upper"
# As our predictions add up, we have an increasing amount of past and a decreasing amount of future

out = torch.triu(torch.ones(5, 5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [13]:
out = torch.zeros(5, 5).masked_fill(torch.tril(torch.ones(5, 5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [14]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [17]:
# Transposing is when we flip the tensor
# In this example we are swapping the 0th dimension with the 2nd dimension

input = torch.zeros(2, 3, 4)
out = input.transpose(0, 2)
out.shape

torch.Size([2, 4, 3])

In [18]:
# Stack the tensors; these tensors are vectors, so stacking them will turn them into a matrix

tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
tensor3 = torch.tensor([7, 8, 9])

stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [20]:
import torch.nn as nn

sample = torch.tensor([10., 10., 10.])
linear = nn.Linear(3, 3, bias=False)
print(linear(sample))

tensor([ 5.3657,  1.8826, -6.8979], grad_fn=<SqueezeBackward4>)


In [21]:
# Softmaxing a vector is to:
# 1.) Exponentiate each value
# 2.) Find the sum of each value
# 3.) Divide each exponentiation by the sum

import torch.nn.functional as F

tensor1 = torch.tensor([1., 2., 3.])
softmax_output = F.softmax(tensor1, dim=0)

print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [26]:
# Embedding vectors are dense, low-dimensional respresentations of high-dimensional data

# Initialize an embedding layer
vocab_size = 1000
embedding_dim = 100
embedding = nn.Embedding(vocab_size, embedding_dim)

# Create some input indices
input_indices = torch.LongTensor([1, 5, 3, 2])

# Apply the embedding layer
embedded_output = embedding(input_indices)

# The output will be a tensor of shape (4, 100), where 4 is the number of inputs
# and 100 is the dimensionality of the embedding vectors
print(embedded_output.shape)

torch.Size([4, 100])


In [31]:
# Matrix multiplication in Python

a = torch.tensor([[1, 2],[3, 4],[5, 6]])
b = torch.tensor([[7, 8, 9],[10, 11, 12]])

print(a @ b)
print(torch.matmul(a, b))

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [35]:
int_64 = torch.randint(0, 2, (3, 2)).float()
float_32 = torch.rand(2, 3)

result = torch.matmul(int_64, float_32)
print(result)
print(int_64)

tensor([[0.0000, 0.0000, 0.0000],
        [0.0990, 0.7072, 0.4201],
        [0.5252, 0.8142, 1.1781]])
tensor([[0., 0.],
        [1., 0.],
        [1., 1.]])
