In [10]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [15]:
# Define the input tensor
x = torch.tensor([-0.05], dtype=torch.float32)

# Create an instance of the ReLU activation function
relu = nn.ReLU()

# Apply the ReLU activation function to the tensor x
y = relu(x)

# Print the output
print(y)

tensor([0.])


In [11]:
x = torch.tensor([-0.05], dtype=torch.float32)
y = F.sigmoid(x)

print(y)

tensor([0.4875])


In [12]:
x = torch.tensor([-0.05], dtype=torch.float32)
y = F.tanh(x)

print(y)

tensor([-0.0500])


In [14]:
# Define the input tensor
x = torch.tensor([-0.05], dtype=torch.float32)

# Create an instance of the ReLU activation function
lrelu = nn.LeakyReLU()

# Apply the ReLU activation function to the tensor x
y = lrelu(x)

# Print the output
print(y)

tensor([-0.0005])
